SECTOR_JA = {
    "Consumer Cyclical": "一般消費財・サービス",
    "Consumer Defensive": "生活必需品",
    "Communication Services": "コミュニケーション・サービス",
    "Industrials": "資本財",
    "Technology": "情報技術",
    "Healthcare": "ヘルスケア",
    "Financial Services": "金融",
    "Real Estate": "不動産",
    "Utilities": "公益事業",
    "Energy": "エネルギー",
    "Basic Materials": "素材",
}

INDUSTRY_JA_EXAMPLES = {
    "Residential Construction": "住宅建設",
    "Auto Manufacturers": "自動車メーカー",
    "Semiconductors": "半導体",
    "Software—Application": "ソフトウェア（アプリ）",
    "Banks—Regional": "銀行（地域）",
    "Software - Application": "ソフトウェア（アプリ）",
    "Banks - Regional": "銀行（地域）",
    "Asset Management": "資産運用",
    "Insurance - Life": "生命保険",
    "Insurance - Property & Casualty": "損害保険",
    "Real Estate Services": "不動産サービス",
    "Construction & Engineering": "建設・エンジニアリング",
    "Electronic Components": "電子部品",
    "Airlines": "航空会社",
    "Railroads": "鉄道",
    "Steel": "鉄鋼",
    "Chemicals": "化学",
    "Oil & Gas Integrated": "石油・ガス総合",
    "Electric Utilities": "電力会社",
    "Telecommunications Services": "通信サービス",
    "Food Products": "食品",
    "Beverages - Alcoholic": "アルコール飲料",
    "Beverages - Non Alcoholic": "非アルコール飲料",
    "Retail - General": "小売（総合）",
    "Department Stores": "デパート",
    "Specialty Retail": "専門小売",
    "Entertainment": "エンターテイメント",
    "Gaming & Casinos": "ゲーム・カジノ",
    # 必要に応じて増やす
}